- documentation.markdown
> Update course documentation

- community.markdown
Let's add this one! I talked to the owner of the group on Meetup.com and they're okay with being added to the list.
> Community: Add Haskell DC

- documentation.markdown
> Adds book "Haskell from the Very Beginning"

- community.markdown
- templates/nav.html
closes #53
I made a comment in reddit about how it was difficult to find the donations area and donate.  I got a reply back to submit a PR to address this.  I had trouble getting nix and cabal to work on my mac (need to switch back to linux) so I used stack to test this out and removed all the stack files.  Let me know if there are any questions or other modifications that I need to make.
> Added donation links

- community.markdown
Our meeting exists since 2011 and meets monthly. Please add it to the list.
> community: Add Munich Haskell Meeting

- default.nix
- donations.markdown
This should address #68.
I also fixed the link from the donations page to the committee page.
> Fixed link to Amazon Smile and added a more info link.

- css/hl.css
- index.html
- js/glider.js
- js/home.js
- templates/default.html
- templates/testimonials.html
- testimonials/company-c.yaml
- testimonials/company-d.yaml
- testimonials/company-e.yaml
Hello I am a developer of strivelabs, we have developed the HTML and style of a carousel for the testimonal section on the index. The attachments should let you see the result
https://user-images.githubusercontent.com/26113462/124448688-01779300-dd83-11eb-83b9-819ce8efd300.mp4
> Add testimonial section to index

- community.markdown
Fixes https://github.com/haskell-infra/www.haskell.org/issues/98
> Remove dead link to theTUNDRA community

- documentation.markdown
> Move the Yesod book to intermediate books

- testimonials/foxhoundsystems.yaml
I'm one of the Co-Founders at Foxhound Systems. I didn't really provide a great quote in my original email to the Haskell committee, since I thought only company name and logo would be included. I provided a better quote in this PR, one that emphasizes why Haskell specifically is a great language.
> Update Foxhound Systems testimonial

- testimonials/centralapp.yaml
> fix missing 's'

- testimonials/finn.yaml
As reported by Sjur Millidahl.
> Capitalise FINN

- README.md
to ensure they don't get out of sync
> Link to admin contact details

- site/documentation.markdown
> Mark paid resources

- site/irc.markdown
> Provide IRC web client link

- site/documentation.markdown
> Suggest introductory resource

- site/downloads.markdown
Originally part of https://github.com/haskell-infra/www.haskell.org/pull/125 but logically separate so it seems better to consider it separately.
> Add link to stack bindist

- site/downloads.markdown
Closes https://github.com/haskell-infra/www.haskell.org/issues/175
> Make the internal GHCup links point somewhere

- README.md
Updates to the README, particularly to make it easier for community contributors to get started.
> Updates to README for community contributions

- site/documentation.markdown
I think it is important for readers of the report to know how GHC differs.
> Add link to differences between GHC and the language report

- site/downloads.markdown
> Capitalize Haskell Stack in documentation

- site/css/hl.css
> use flexbox to "stick" footer at page bottom

- site/documentation.markdown
Placing free resources first makes sense and is more visually appealing.
> Documentation page: place free resources first

- site/documentation.markdown
See #218 for details. (Thanks @avanegas-carecloud!)
> Beginning Haskell is an earlier edition of Practical Haskell

- site/index.html
Closed one "row" in correct place, opened new one after it.
Added one "row" where it was missing.
Improved formatting for `<br>`s so they are visible when looking at code.
No visual changes to the landing page, this is just refactoring.
> Fixed Boostrap mistakes on landing page.

- site/css/hl.css
https://user-images.githubusercontent.com/13085980/216604768-d1b1876e-354a-4f60-8e3e-46e83dbaf0fd.mp4
Fixes #246
> Fixing the mobile horizontal scroll issue

- site/templates/nav.html
> Display the playground in the navbar

- site/documentation.markdown
Closes https://github.com/haskell-infra/www.haskell.org/issues/263
> Remove dead link

- site/templates/default.html
This pixel will let us start using Scarf for analytics on haskell.org and related pages, as ratified in [Haskell.org committee proposal #13][1].
[1]: https://github.com/haskell-org/committee/pull/13
> Include Scarf tracking pixel

- site/css/hl.css
> Increase contrast of nav link text

- site/documentation.markdown
- site/get-started.markdown
Can be verified in the [source repo](https://github.com/soupi/learn-haskell-blog-generator/commit/1c18e4d6497e439ce18ddc4249555e9891328a1c).
Thank you.
> lhbg has a new domain

- site/community.markdown
With two Aussie confs on this list, and having attended and presented at Curry On 2018, I take no pleasure at all in submitting this PR :(
> Remove some dormant/defunct conferences

- site/documentation.markdown
Similar to https://github.com/haskell-infra/www.haskell.org/pull/298
> Update LYAH link to a working one

- site/documentation.markdown
I'd like to add my book to the list. :)
> Add 'Learn Haskell by Example'

- README.md
These were out of alphabetical order, which was confusing.
> Alphabetize subsites

- site/index.html
Move the Scarf entry into its place to avoid leaving a gap
----
We are grateful to Equinix for many years of very generous sponsorship!
@jmct, can you confirm  you think this is the right thing to do?
> Remove Equinix as sponsor

- site/index.html
As per https://github.com/haskell-infra/www.haskell.org/pull/340#issuecomment-2874082267
@jmct can you give sign off on this? And is the wording for Digital Ocean OK?
> Remove Galois sponsorship, add Digital Ocean
