haskell-infra/www.haskell.org

- community.markdown
The link to POPL is outdate. The link to the _Symposium on Trends in Functional Programming_ is also outdated, which brings the question: shouldn't we reevaluate which conferences should be linked in this page? Are all these conferences still active?
> Update link to the POPL conference

- index.html
In the _Lazy_ section of the main page of www.haskell.org, there is a typo. I suppose it should be `original` instead of `orginal`.
> Fix a typo on the main page

- community.markdown
- donations.markdown
[Axman6 on Reddit][reddit] suggested that we should have a more official-looking donation page rather than using the Wiki, which seems like a great idea. 
This PR creates a donation page with text based on [my request for donations][request] and [the old donations Wiki page][wiki-page]. It also adds a short blurb and link to the donations page from the Community page.
The biggest practical change compared to the Wiki page is that I did not list the option to donate through SPI—as far as I can tell, there is no reason for us to funnel people there over PayPal and checks directly to Haskell. I'm happy to add that note back in if there are compelling reasons for it!
[reddit]: https://www.reddit.com/r/haskell/comments/ef9elt/supporting_haskellorg/fbzv2pe/
[request]: …
> Created an "official" page describing how to donate to Haskell.org.

- irc.markdown
This PR adds the `#haskell-docs` channel to the list
> Add the #haskell-docs channel to the list

- css/hl.css
I was helping somebody install Haskell and they had trouble identifying links from body text. Being able to easily distinguish links from text is both a usability and an accessibility consideration, so we should do something to make this clearer.
Based on the WCAG guidelines on [link color], we have two options: 
* Add a non-color way to distinguish links (ie an underline).
* Ensure the link color has a 3:1 contrast ratio with the body text color¹.
With this in mind, if we wanted to keep links defined by color only, we would need a color that:
* Has a 3:1 contrast ratio with our text color (#333)
* Has a 4.5:1 contrast ratio with our background color (white)
* Matches the overall color scheme of the site (purple)
I spent some time trying to find a color like this, but couldn't find one …
> Made links easier to distinguish by giving them a dotted underline.

- downloads/linux.markdown
- stack is now in Fedora
- fedora modules have later ghc
- stack-2.3 copr
- newer ghc coprs for RHEL
> linux: update Fedora and EPEL entries

- .gitignore
- default.nix
- haskell-org.cabal
This ensures we're using a more recent GHC release and generally more recent packages. Apart from keeping us up to date, this should also let Nix fetch more packages from the public binary caches, saving on build time.
This required bumping the Hakyll requirement in the .cabal file to `4.13.*`.
The site still builds correctly with all of these changes.
> Bumped default Nixpkgs to a rev from 20.03 and GHC to 8.8.3.

- haskell-org.cabal
This makes the licensing of the package clear and ensures it can be used without globally configuring `allowUnfree = true` in Nix.
> Added the license field to the .cabal file.

- downloads/linux.markdown
The Arch package for `haddock` is called `haskell-haddock-library` rather than just `haddock`.
This should address #28.
> Updated the command to install Haskell tools on Arch.

- donations.markdown
- haskell-org-committee.markdown
- index.html
This adds an "official" page describing the Haskell.org non-profit and the Haskell.org committee. The content is based on the [Haskell.org committee wiki page][wiki], edited a bit for focus and clarity.
Over time, I expect this page will cover more details about how the committee operates and makes decisions—this is the first step to making the committee's activities and structure more transparent to the community.
[wiki]: https://wiki.haskell.org/Haskell.org_committee
> Page describing Haskell.org and the Haskell.org committee

- default.nix
With this change, I was able to run `buildAndWatch` from a Nix shell without running into Unicode errors (see #29 for details).
> Explicitly set LOCALE_ARCHIVE and LC_ALL inside nix-shell.

- irc.markdown
The IRC page was quite out of date. ircbrowse.net no longer exists and is being squatted on!
> Remove link to spam site from IRC page

- community.markdown
- haskell-org-committee.markdown
- Add some committees to the community page
- Extend the haskell.org committee page with more details on how we look for members
> Extend committee page

- downloads.markdown
... rather than the paragraph text
The internal links to the Minimal installers and Haskell Platform sections of  https://www.haskell.org/downloads/ jump to the paragraph text below the section title, not the section title itself.  (The link to Stack doesn't but by accident rather than by design, I think. pandoc seems to add `id="stack"` to the header, which is preferred over the `<a name="stack">`).
I found this rather disorienting. When I click on an internal link I expect to go to a section header that reflects what I just clicked. I'm sure linking to the paragraph text was done to save the reader time and/or screen space but for me at least it was psychologically unsettling.
How about this PR to switch to behaviour which is, I believe, more common?
> Make internal links jump to the header

- js/tryhaskell.pages.js
This should fix #55 .
Made it similar to https://tryhaskell.org/ (which is a backend for the sandbox).
> Remove obsolete IO actions from sandbox suggestions

- haskell-org.cabal
This ensures there are no conflicts with other hakyll sites (that might create another executable called `site`).
> haskell-org.cabal: rename site executable --> haskell-org-site

- haskell-org-committee.markdown
This gets the Committee page up-to-date and fixes #62.
> Updated list of committee members for 2021.

- community.markdown
This adds a link to the very informative https://github.com/haskell-infra/haskell-admins/ page about how the Haskell core infrastructure is administered.
> Link to Haskell admin team GitHub repo

- default.nix
In #63 we renamed the executable from `site` to `haskell-org-site` to avoid collisions with other projects. However, we didn't update the name in the `default.nix` file, which broke the `buildAndWatch` command in the Nix shell.
This PR fixes that problem.
> Fix buildAndWatch command in nix-shell

- README.md
Back in 85befe2c555834a217fb65655e864e147bf9b5d4 the `site` executable was renamed to `haskell-org-site`. This commit updates the README to sync with that change.
> README: correct 'site' to 'haskell-org-site'

- donations.markdown
This contributes to #59, moving authoritative content from the wiki to the primary haskell.org website.
We can update with commits to clean it up, but ATM this is the content from that page, more or less as-is. 
After this is cleaned up and live, we can then update the wiki page to replace its content with a link back to this donations page on haskell.org.
> donations: copy content from https://wiki.haskell.org/Donate_to_Haskell.org

- haskell-org-committee.markdown
Tom Ellis replaces Emily Pillmore after she left to become Haskell
Foundation CTO.
> Update haskell.org committee members

- README.md
... and add link to ghcup subsite
Fixes https://github.com/haskell-infra/www.haskell.org/issues/77
> Reinstate link to Haskell Platform repository

- irc.markdown
given discussion on https://www.reddit.com/r/haskell/comments/nfqw0t/thoughts_on_the_state_of_the_freenode_irc_network/ and elsewhere, people have begun migrating from the haskell group of channels on freenode to libera.chat, which is where the freenode admins and ops have migrated following the hostile takeover.
This is a PR to update the haskell website accordingly. It might take a day or two for it to become evident that this is the clear direction of the community, but most trusted #haskell ops have made the shift at this point (and some are even libera volunteers directly), so by the time this PR is approved and merged, I imagine it will be obviously accurate.
> freenode -> libera.chat

- irc.markdown
The language channels are wrong for the new network. Its causing confusion.
> Fix haskell language channel names for new network

- index.html
It appears this domain is no longer pointing towards a legitimate service, at least as of Feb 13th 2021:
* https://www.domainiq.com/domain?webmon.com
It might be best to remove this link from the https://www.haskell.org, at least for now.
Currently, the domain is parked on both 443 and 80:
> Remove broken webmon.com link

- .github/workflows/main.yml
- .gitignore
- community.markdown
- default.nix
This PR cleans up our GitHub action definition and generates a zip file with the site contents as an artifact.
The upload-artifact@v2 action had trouble with symlinks (see [this issue][1]), so we needed to specify the path as a glob.
Next steps: automatically deploy the site if it builds and passes our checks. This will require managing SSH keys in CI.
[1]: https://github.com/actions/upload-artifact/issues/92
> Create a Zip File with GitHub Actions

- community.markdown
The Matrix Space includes bridges to the IRC channel like #haskell as well.
Here's a screenshot of our "room tree".
> Add link to Haskell Matrix Space

- README.md
- buildAndWatch
- builder/default.nix
This change is intended to make it a little bit easier for new contributors to get started, and to address an issue with the buildAndWatch shell alias inside of the nix shell.
Change summary:
- Remove the `buildAndWatch` shell alias from the builder's nix-shell, since this didn't seem to work properly
- Add a `buildAndWatch` shell script that provides the same functionality as the shell alias, but runs from outside of a nix shell
- Update the README file to point to the new `buildAndWatch` script, and to try to present an easier to follow workflow for making changes.
> refactor buildAndWatch to run outside of the nix shell

- .github/workflows/deploy.yml
- README.md
- default.nix
- deploy.sh
This PR adds a Github Action to build the website and deploy it to the haskell.org server.  We deploy the site *only* on
1. A push to `master`, or
2. A manually triggered Deploy build
(We don't want to deploy for every branch and PR of course!)
I have tested this on my fork. See https://github.com/tomjaguarpaw/www.haskell.org/runs/2678438965?check_suite_focus=true for a successful (dry run) deployment.
(Closes https://github.com/haskell-infra/www.haskell.org/issues/83)
> Automatically deploy site

- js/glider.js
- js/home.js
- templates/testimonials.html
Before this change, testimonials would be squeezed uncomfortably tight on narrow viewports. This PR sets the width to 300px unconditionally, and also deletes a couple of confusing static files related to the `glider.js` widget but apparently not used.
After the resize:
cc @rebeccaskinner
> resize testimonials to 300px wide

- documentation.markdown
The first edition is no longer being sold, so this new link points to the second edition.
> Update Fun. Design and Arch. book link

- builder/Testimonial.hs
- builder/site.hs
- templates/testimonials.html
- testimonials/bellroy.yaml
- testimonials/bitnomial.yaml
- testimonials/calabrio.yaml
- testimonials/centralapp.yaml
- testimonials/ebot7.yaml
- testimonials/finn.yaml
- testimonials/foxhoundsystems.yaml
- testimonials/hasura.yaml
- testimonials/imagineai.yaml
- testimonials/iohk.yaml
- testimonials/mercury.yaml
- testimonials/noredink.yaml
- testimonials/scarf.yaml
- testimonials/serokell.yaml
- testimonials/stackbuilders.yaml
Closes #118 
This change makes the logos in the testimonial section link back to the companies that gave them. I've added links to all of the companies, so in addition to the merits of the code change, it would be probably be a good idea for someone to double-check I got all of the links correct.
> Add company backlinks to testimonial logos

- downloads.markdown
As per https://github.com/haskell-infra/www.haskell.org/pull/125#discussion_r687070791
@hasufell Could you confirm this is correct?
> Apple Silicon is now supported!

- downloads.markdown
Message after @tomjaguarpaw's changes
The specifics of this change are to replace Chocolatey with ghcup as the preferred installation method of GHC, cabal-install and haskell-language-server on Windows. The overall effect is that the install instructions become common over Windows, Linux and MacOS.
In my view this makes something better without making anything worse.  However, the Haskell.org committee can't proceed to merge this without broad community input.
Counterpoints:
* @parsonsmatt suggests that ghcup on Windows is not sufficiently well-tested.
----
@bodigrim's original message
Since #93 has descended into chaos, I’ll take a risk to suggest an alternative, more conservative approach, which merely mentions that ghcup supports Windows and can install Stack, but does not go any …
> Update downloads page

- documentation.markdown
The link is not only irrelevant at this point, it's also unavailable.
> documenation page: remove Cabal sandbox reference

- testimonials/README.md
Adds a note to the testimonial README that the preferred logo size is 300x300px
> Add logo dimensions to testimonial README

- README.md
It would be very helpful to collect the list of `www.haskell.org` subsites in one place. Eventually I would like to gather more information about their source and owners.
The table is split into two sections: subsites that are reasonably up-to-date and subsites that aren't. Within the sections the subsites appear in alphabetical order..
> List subsites

- site/documentation.markdown
Can I add [lhbg](https://lhbg-book.link) to the list of intro books under the documentation page?
> Add lhbg to list of introductory books

- site/downloads.markdown
I'm not 100% sure Stack supports FreeBSD so I asked them: https://github.com/commercialhaskell/stack/issues/5674. Even if it doesn't I think it's better to merge this and adjust the Stack info later.
> Specify which systems the installation instructions support

- site/platform.markdown
and link to the Downloads page instead
Part of:
* https://github.com/haskell-infra/www.haskell.org/issues/164
* https://github.com/haskell-infra/www.haskell.org/issues/165
> Add platform/ page describing that the Haskell Platform is deprecated

- site/downloads.markdown
"Linux" should be capitalized. See, e.g., [Wikipedia](https://en.wikipedia.org/wiki/Linux).
> Capitalize "Linux"

- site/downloads.markdown
It seems that [Stack doesn't support FreeBSD](https://github.com/commercialhaskell/stack/issues/5674) so we should probably note that fact.
> Note that Stack does not support FreeBSD

- site/irc.markdown
The logs don't seem to have survived the move to libera.
> Remove outdated irc log link

- README.md
Link to the source of the `/alex` subsite.
> Link to the source of the `/alex` subsite

- site/downloads.markdown
The links will go out-of-date less quickly so will be easier to maintain.
The original patch was by @hasufell. Some changes were made by @tomjaguarpaw.
> Remove distro-specific instructions and only leave links

- builder/haskell-org.cabal
When trying to build/run the site locally with GHC 9.2.2 I needed to change the hakyll upper bound. I could have gone incrementally to 4.15.x to find a version that could still build, but found it easier to bump it all the way to 4.16. Haven't seen any breaking changes in the hakyll changelog in the 4.14 -> 4.15.latest changelist.
> bump hakyll upper bound to <4.16

- site/downloads.markdown
As discussed in https://github.com/haskell-infra/www.haskell.org/issues/170#issuecomment-1092032433
I have appended the NixOS entry to be polite. I wonder if there could be a more principled approach to ordering the entries.
At the moment I guess it’s "felt importance"? Alphabetically might be an improvement. Sadly the Haskell survey does not ask for the distributions that people primarily use.
Note: It is our aim to improve and move the documentation. Still the current documentation is a lot better than nothing. So I think we should put the link here for the while. I will update it as soon as we made progress on this.
> downloads: Add entry for NixOS 

- site/documentation.markdown
The source repo is not particularly useful.  Let's not remove it for
now, but giving the `git clone` command seems overly specific.  People
that need to clone the repo typically already know how to do it.
Also merge the paragraphs to make this one short paragraph, otherwise
we're making this marginal interest look more useful than it is.
> Simplify Language Report section of Documentation

- site/testimonials/mercury.yaml
Minor change to Mercury's copy on the testimonials section to comply with some marketing regulations on the use of the term "bank"
> mercury is not a bank

- site/documentation.markdown
I wasn't able to test this locally, buildAndWatch ended with an error `[ERROR] _cache/a98f5fd1dec8ada591e76ae4112817f9 for Hakyll.Core.Resource.Provider.MetadataCache/community.markdown/body: Store.set: invalid argument (invalid byte sequence)`, but I'm fairly sure it is correct, and this resource has been mentioned several times in the subreddit.
> Add haskell.mooc.fi

- site/community.markdown
Tiny PR. Fixes an indirect link to the Wiki and then to GitHub.
> fix indirect link (core libraries committee)

- site/downloads.markdown
In my opinion, the time is right for www.haskell.org to recommend GHCup as the single install tool, for the following reasons:
* It is desirable for users to have a single way to install all of the Haskell toolchain. It is confusing to recommend they use two different installers.
* GHCup has proven to be a reliable installation tool for the Haskell toolchain.
* GHCup has been able to install Stack for the last 15 months
* GHCup [can now manage GHC versions for Stack](https://gitlab.haskell.org/haskell/ghcup-hs/-/merge_requests/285)
* GHCup installs both cabal-install and Stack by default, so it is not "biased" towards one or the other
* The current GHCup and Stack [have been collaborating](https://github.com/haskell-infra/www.haskell.org/issues/212#issuecomment-1272561149) to make sure …
> Recommend installing Stack via GHCup

- site/index.html
The button redirects to the downloads page for now, but we can update that if we add a getting started page and think that that's a better link target.
Credit to @Martinsos
> Add a big friendly button: "Get Haskell"

- site/downloads.markdown
Tiny PR.
To be honest, I do not understand the sentence (quote):
```
For Nix the package manager on the distribution NixOS and other OS:
```
Does this mean that this advice is applicable to the Nix package manager on all operating systems? If so, I suggest using:
```
For the Nix package manager:
```
or probably better
```
When using the Nix package manager please note:
```
(But then, only NixOS is referenced in the first point).
So maybe we want to fix that right away?
> nit: punctuation

- site/community.markdown
Looks like the current link leads to a 404. I found a URL to the mailing list page on we.lurk.org that works.
Addresses #229
> Fixed link to Haskell Art mailing list

- buildAndWatch
This should fix the problem reported in #29
> Explicitly set locale to C.UTF-8 inside buildAndWatch script

- site/downloads.markdown
What happened here is that I removed "btn-primary" class from the 4 buttons at the bottom of the Downloads page, where each of these buttons on click expands into detailed instructions for installation of Haskell toolchain via native OS package manager for specific distribution.
Instead, I put it on GHCup, which is the recommended installation method.
This is what it looked like before:
This is what it looks like now:
I removed it because I felt confident that it was a mistake in the earlier design. The main thing we want visitors to focus on this page is GHCup, then explanation of the toolchain, and only then potentially the installations via native OS package manager. So it is the part of the page that we want to attract the least of the attention, we even have text that says this …
> Fix link emphasis on Downloads page

- site/css/hl.css
- site/downloads.markdown
- site/get-started.markdown
- site/index.html
- site/templates/nav.html
@tomjaguarpaw here comes the new PR, since the last one got messed up!
You mentioned how it is better to get stuff that is a clear win in first, and then do the rest -> all good with me, and I am also ok on modifying this PR and dropping what is needed in order to get it in, I think regardless of exact shaping of words and similar, the value it brings is about the same and big, so that is my focus.
I will be gone for the next 2 weeks for a trip so I won't be able to work on this, but feel free to modify and add to it as needed.
@soupi and @lsmor are also very knowledgeable about the effort and can help finalize it without me, if needed.
NOTE: I haven't tested this PR! I normally do it by running `./buildAndWatch cabal` but now it got stuck on building pandoc and is not finishing, and I …
> Added get-started page.

- site/get-started.markdown
haskell.org has a pretty good IRC page, lean, informative, with clear onboarding instructions. Let us use that instead of the one on the wiki.
> Use haskell.org IRC page

- buildAndWatch
- builder/site.hs
- default.nix
This change makes sure that the site executable *always* expects UTF-8, regardless of any locale environment variables. This should avoid problems like #29 and #249 in a more robust way than trying to set the right environment variables in `buildAndWatch` or `shell.nix`.
The diff ended up a bit noisy because of indentation changes; the key change was adding `Encoding.setLocaleEncoding Encoding.utf8` to the beginning of `main`.
I tested this by reproducing the Unicode error (using `nix-shell --pure`) and checking that the Haskell code change fixes the problem.
> Explicitly set local encoding to UTF-8 in site.hs

- site/js/jquery.console.js
Cherrypicked fix provided in https://github.com/chrisdone/jquery-console/pull/71.
Tested on desktop, iOS, and Android - with Android now working. There is also another [comment](https://github.com/chrisdone/jquery-console/pull/71#issuecomment-364102640) confirming the fix.
Fixes https://github.com/haskell-infra/www.haskell.org/issues/252
I would welcome another person making sure "try it" is still working on desktop as before (comparing with currently deployed https://haskell.org).
Hint for review: I needed to change the listening host to `0.0.0.0` in order to be able to access the local dev server via my mobile device in the same network.
```patch
diff --git a/builder/site.hs b/builder/site.hs
index c5869dd..a56877b 100644
--- a/builder/site.hs
+++ b/builder/site.hs
@@ -66,7 +66,7 @@ …
```
> Fix try haskell on Android

- site/haskell-org-committee.markdown
All decided by unanimous vote, 25th January 2023, except Ryan Trinkle treasurer, a position he has held for several years already.
> Update committee positions

- site/get-started.markdown
When I try new software, I am always wary of installers requiring root access, as I don't want to turn my system into a [FrankenDebian](https://wiki.debian.org/DontBreakDebian). Specifying that GHCup is well behaved in this regard might be of importantce to a sizeable portion of users.
I would like this information to be present, but also to be as unobtrusive as possible (it is a "Get Started!" page, saddling it with too many things is counterproductive), so I welcome suggestions on where to put this.
> State that GHCup does not require root access

- site/documentation.markdown
Hey everyone 👋🏻 
I would like to propose the addition of my Haskell Beginners Course 2022 to the `Tutorials` section of the `Documentation` page at Haskell.org:
* https://github.com/haskell-beginners-2022/course-plan
My course has the following features:
* 🆓 It's free
* 💎 I keep it updated
* 📜 The course provides a certificate upon completion
* 📽️ It's rather popular (~20K views on YouTube and ~600 stars on GitHub)
* 🧑‍🏫 I still review solutions weekly
* 👪 Hundreds of people applied and dozens finished successfully
So I believe it could be a good addition to the website documentation page 😌
> Add Haskell Beginners Course 2022 to Documentation

- builder/site.hs
These redirects are for links in the paper "A History Of Haskell: Being Lazy With Class."
The `createRedirects` function produces html with meta tag redirects ([source](https://jaspervdj.be/hakyll/reference/src/Hakyll.Web.Redirect.html)). I think this should properly handle the following URLs:
- https://www.haskell.org/humor -> https://wiki.haskell.org/Humor
- https://www.haskell.org/hat -> https://wiki.haskell.org/Hat
- https://www.haskell.org/development/views.html -> http://web.archive.org/web/20040107202217/http://haskell.org/development/views.html
Fixes #261.
> Add redirects for old urls

- .github/workflows/deploy.yml
- .github/workflows/main.yml
Updating install-nix-action should fix #266 (see [cachix @144][1]). I also noticed that `deploy.yml` was not using cachix-action at all, so I updated that as well.
Since we're updating the workflows anyhow, I figure we can also bump `cachix-action` while we're at it—same change as #265 but applied to both workflow files.
> Update install-nix-action and cachix-action

- site/index.html
Data Dog used to provide monitoring service for us, but looks like we don't use them any more. (See #269 and https://github.com/haskell/play-haskell/issues/21#issuecomment-1570595269)
> Removed Data Dog from sponsorship list

- site/css/hl.css
In trying to improve the appearence of the Haskell main webpage a little bit, I've
1. Removed the underline of links that appear
* inside buttons
* in the navbar
2. Changed the dotted underline to a solid underline
Screenshots:
Old:
New:
I suppose the dotted vs solid underline decision is more contentious, so I've added it as a separate commit we can also just drop.
Thanks!
> Fix styling of links

- site/templates/default.html
**Issue**
This recent [PR](https://github.com/haskell-infra/www.haskell.org/pull/274) added a Scarf tracking pixel. While the link is indeed to a 1px by 1px image, it's currently taking a lot of space at the bottom of the page because it's a flex item.
cc: @TikhonJelvis (stakeholder; added the pixel)
**Summary of changes:**
- remove pixel from flow of page with absolute positioning
- use existing `invisible` class to add `visibility:hidden`
**Testing**
- ensured the pixel is still being loaded by looking at Network tab
- clicked around the site to make sure nothing else started looking funky
---
Demos
**CURRENT**
**AFTER**
> Hide tracking pixel

- site/js/jquery.console.js
Currently, if you visit [haskell.org](https://www.haskell.org/) and attempt to navigate with the keyboard, you will find that it's impossible to go through the entire page. This is a major a11y concern, as many users rely on keyboard navigation, often with a screen reader, to navigate sites. Closes #10.
**Summary of changes:** This diff handles the pressing of the "tab" key by removing focus from the current element using the [blur](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/blur) (bad name, IMO) method, and removing the current `doComplete` callback on tab. I also made sure the right styling is applied when focusing on the console by tabbing.
**Testing**
- Browsers used: Firefox, Chrome
- I tabbed through the document and made sure we can land on and leave the console. …
> Fix keyboard trap

- site/index.html
As discussed directly with @TikhonJelvis and @idabzo, following up with a sponsorship entry for Scarf. Happy to make any verbiage tweaks you feel are needed!
> Add Scarf sponsorship entry

- site/documentation.markdown
"Effective Haskell" is not in beta stage anymore, since august 1st
> update "Effective Haskell" entry

- site/index.html
- site/templates/default.html
- site/templates/nav.html
- site/templates/testimonials.html
Mainly, adding the `alt` attribute where needed.
`alt` with no value means the image is for decoration only, like the video thumbnails.
> Fix small text a11y issues

- site/documentation.markdown
The website domain has been changed.
Fixed it to point to the right course of 2013, since 2023 course has no materials.
> CIS 194 domain has changed

- site/irc.markdown
Perform the following updates to the IRC page:
- Remove mentions of the Freenode -> Libera migration, which was 3 years ago now.
- Demote the link to old Freenode logs; it is no longer important enough to warrant a separate heading.
- Extract regional and language-specific channel list to its own section.
- Reorder the general channel list to prioritise more popular/important topics (according to me).
- Add the `#haskell-infrastructure` channel to the general list.
> update irc page

- site/css/hl.css
It causes layout issues on mobile
Before:
After:
> Remove alternative-logo padding

- site/templates/default.html
The alternative logo persisting causes a bit of surprise from users, and it's difficult to indicate how to turn it off. This removes the persistence, making the alternative logo only available only when the parameter is present.
> Enable alternative logo only when the parameter is present

- site/documentation.markdown
This PR adds Haskell Language Server to the documentation page
> Add Haskell Language Server to the documentation page

- site/get-started.markdown
As of recent, https://learnyouahaskell.com/chapters lost any CSS / JS because of hard-coded `<base href="http://learnyouahaskell.com/">` (modern browsers are not keen to leave safety of HTTPS). Let's point to https://learnyouahaskell.github.io, which is a community-maintained fork. Besides working CSS, it is more up to date with modern ecosystem.
> Update LYAH link to a working one

- site/documentation.markdown
- site/donations.markdown
The course doesn't appear to be complete yet but I didn't think it hurt to add the link now since there looks to be good content available.
> add a link to Well-Typed's introduction to haskell series

- site/security.markdown
- site/templates/nav.html
Fixes: https://github.com/haskell-infra/www.haskell.org/issues/293
Many thank @aespaze42 for your contribution!
Ping @blackheaven @mihaimaruseac
> Add a Security page (#293)

- .github/workflows/deploy.yml
- .github/workflows/main.yml
Don't merge yet. Creating a draft PR so that we can see how some things react in live CI.
Update: Ready to merge.
> Fix cachix failures

- site/community.markdown
This conflicts with https://github.com/haskell-infra/www.haskell.org/pull/301, so when one is merged the other will have to be rebased.
> Remove London Haskell, because it is not longer active

- site/community.markdown
I just founded this meetup and I would like to add it to the community page! 😸
This commit also moves the London Haskell meetup to be in alphabetical order because OCD
> Add Portland Has Skill meetup

- site/haskell-org-committee.markdown
Given my knowledge as the current Secretary of Haskell.org, Inc., I have suggested some updates to this page for the website Committee to consider, as follows. I have also reformatted existing content to avoid long lines. There are no substantive changes other than those identified in the points below. In particular, I have made no changes to the description of how the Committee itself is constituted or governed.
* For the benefit of non-US readers, I have clarified that '501(c)(3)' is a reference to the US Internal Revenue Code of 1986. I have also distinguished the legal form (New York State Not-for-Profit Corporation) from the US tax status (tax exempt).
* I have used 'the Committee' consistently for the committee (and introduced that term).
* I have used 'the corporation' rather than …
> Updated info about Haskell.org, Inc.

- README.md
- site/community.markdown
- site/documentation.markdown
- site/donations.markdown
- site/index.html
- site/irc.markdown
- site/mailing-lists.markdown
- Update a heap of links from http: to https:
- Update a handful of links that were dead, but I found a substitute target.
- Remove a handful of defunct conferences from the Community page
- Promote ZuriHac to top of the Hackathons list
- Remove reference to the pre-libera.chat #haskell IRC logs (target went away, and probably the logs with it).
> link updates: https, some fixups, remove defunct

- site/index.html
When @malteneuss was submitting PRs it wasn't clear how to find information about the maintenance of this site: https://discourse.haskell.org/t/emphasize-why-haskell-on-haskell-org-landing-page/12036/35?u=tomjaguarpaw. Hopefully this PR fixes things a bit.
> Clarify the site info

- site/donations.markdown
Amazon Smile has been defunct for a while now: https://www.aboutamazon.com/news/company-news/amazon-closing-amazonsmile-to-focus-its-philanthropic-giving-to-programs-with-greater-impact
> Remove Amazon Smile option from donations.markdown

- site/index.html
An alternative to https://github.com/haskell-infra/www.haskell.org/pull/338
The idea is for this to be **developer centric**. We want to attract foremost developers, not managers. And we want to give a glimpse "behind the scenes", connecting the dots between development experience and language features. It's ok if there are words the reader doesn't understand... that's what should make them curious!
Parts of the text are based on the PR by @malteneuss ...other parts were written from scratch.
----
> Add "Why Haskell?" section (alternative)
